[mqtt]
  [mqtt.broker]
  url = "tcp://localhost:1883"

  [mqtt.message]
  size = 100
  format = "text"
  qos = 2
  retain = false
  payload = ""

  [mqtt.tls]
  mtls = false
  skiptlsver = true
  ca = "ca.crt"

[test]
pubs = 10
subs = 0
count = 10

[log]
quiet = false

[mainflux]
connections_file = "../provision/mfconn.toml"